# This is a basic workflow to help you get started with Actions

name: SlackAction

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # users from #a-cool-project
      - name: Slack Get Members from Channel
        id: slackcall
        uses: shaunaa126/slack-action@master
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}   
        with:
          method: conversations.members
          args: |
            {
              "channel": "C01RJUQRPP0"
            }

      - name: Parse Slack Response
        run: |
          echo ${{ steps.slackcall.outputs.result }}
          echo "Members: ${{ fromJson(steps.slackcall.outputs.result).members }}"
          echo "Json Output: ${{ toJson(steps.slackcall.outputs.result) }}"

      # users add to #a-new-project
      - name: Slack Invite Members to Channel
        id: slackcall2
        uses: shaunaa126/slack-action@master
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}   
        with:
          method: conversations.invite
          args: |
            {
              "channel": "C01RGBRJ29M",
              "users": "U01RJUKQGEA"
            }